apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: remotedev-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{HOST}}
    http:
      paths:
      - path: /
        backend:
          serviceName: remotedev-service
          servicePort: http